// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute("MavenThought Inc.")]
[assembly: AssemblyProductAttribute("Epoch is a library with helper methods and utilities")]
[assembly: AssemblyCopyrightAttribute("MavenThought Inc.")]
[assembly: AssemblyTrademarkAttribute("MavenThought Inc.")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.2.0.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.0.0";
    }
}
